name: Dessin du keymap

on:
  workflow_dispatch:
  push:
    paths:
      - "config/*.keymap"
      - "config/*.json"
      - "keymap_drawer.config.yaml"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: "config/corne_choc_pro.keymap"
      config_path: "keymap_drawer.config.yaml"
      output_folder: "keymap-drawer"
      json_path: "config"
      commit_message: "keymap-drawer : mise a jour du schema"
